### ISSUE TITLE
Not working properly on Intel USB controllers

### ISSUE THREAD

**Issue by rabits** [rabits/esi-maya22-linux#1]
Seems like something wrong with maya22 usb initialization on the recent kernels.

[maya22_lin_win-filtered.pcapng.gz](https://github.com/rabits/esi-maya22-linux/files/1253866/maya22_lin_win-filtered.pcapng.gz)
[maya22_lin_win.pcapng.gz](https://github.com/rabits/esi-maya22-linux/files/1253868/maya22_lin_win.pcapng.gz)

**Comment by rabits** [comment]
Tried to contact alsadevs: http://mailman.alsa-project.org/pipermail/alsa-devel/2017-March/119172.html - no luck.

**Comment by rabits** [comment]
Tool working fine if soundcard was initialized in win VM and switched back to linux host

**Comment by rdmitry** [comment]
In my case (openSUSE Tumbleweed 20170830) maya22-control works fine on my desktop, but does not work on laptop. Same software and setting on both. Also it does not work if I use USB hub in my desktop monitor.

**Comment by Stefsinn** [comment]
The tool appears to not work with certain USB crontollers. I tested with 2 controllers on the same motherboard.

### Status:
Tool and audio interface work with
- [ ] Intel Sunrise Point-H USB 3.0 xHCI Controller
- [x] ASMedia ASM1142 USB 3.1 Host Controller


### System:
- Motherboard: ASUS ROG Maximus VIII Gene
- CPU: Intel i7-6700K
- Audio interface: ESI Maya 22USB
- OS: Arch Linux
- Kernel: 4.13.9-1


### Controllers:
```
# lspci -v
00:14.0 USB controller: Intel Corporation Sunrise Point-H USB 3.0 xHCI Controller (rev 31) (prog-if 30 [XHCI])
	Subsystem: ASUSTeK Computer Inc. Sunrise Point-H USB 3.0 xHCI Controller
	Flags: bus master, medium devsel, latency 0, IRQ 124
	Memory at 2fff000000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: [70] Power Management version 2
	Capabilities: [80] MSI: Enable+ Count=1/8 Maskable- 64bit+
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci

04:00.0 USB controller: ASMedia Technology Inc. ASM1142 USB 3.1 Host Controller (prog-if 30 [XHCI])
	Subsystem: ASUSTeK Computer Inc. ASM1142 USB 3.1 Host Controller
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at df200000 (64-bit, non-prefetchable) [size=32K]
	Capabilities: [50] MSI: Enable- Count=1/8 Maskable- 64bit+
	Capabilities: [68] MSI-X: Enable+ Count=8 Masked-
	Capabilities: [78] Power Management version 3
	Capabilities: [80] Express Endpoint, MSI 00
	Capabilities: [100] Virtual Channel
	Capabilities: [200] Advanced Error Reporting
	Capabilities: [280] #19
	Capabilities: [300] Latency Tolerance Reporting
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci
```

**Comment by rabits** [comment]
Hmmm... Interesting thing. Could I see `uname -a` and distributive versions for both systems?

**Comment by Stefsinn** [comment]
> Could I see `uname -a` and distributive versions for both systems?

Here you go:
`Linux ArchStef 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux`

### Installed dependencies:
- hidapi  0.8.0rc1-2

About distributed versions, what details do you need exactly? I am bit lost on this.

**Comment by rabits** [comment]
I'm just would like to be sure, that it's the same) So I need just to check 16.04 on my working laptop to rename this issue.

**Comment by rabits** [comment]
Tested many xubuntu amd64 versions (14.04, 16.04, 17.10) on my laptop - none of them working properly. But figured out, that on ARM (RaspberryPI 3 "Linux raspberrypi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux") - it's working like a charm. Will try i386 xubuntu images.

**Comment by rabits** [comment]
Nope, seems like it's really something with USB controllers. Both my laptops with Intel controllers not working.
As I remember I developed the application on ASRock motherboard for ARM (odroid-c1 and odroid-c2).

So now I have no idea how to properly debug the application on my hardware (debugging on ARM & amd64 is not a good way). So I need more data (for example Wireshark pcapng) from working and not working platform with similar kernels to determine a difference between USB packets - if someone can capture such data, it will be really helpful.

**Comment by PumbaPe** [comment]
I too have an Intel controller with which the application is not working properly:
```
00:14.0 USB controller: Intel Corporation Sunrise Point-H USB 3.0 xHCI Controller (rev 31) (prog-if 30 [XHCI])
	Subsystem: Dell Device 07be
	Flags: bus master, medium devsel, latency 0, IRQ 127
	Memory at ed110000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: [70] Power Management version 2
	Capabilities: [80] MSI: Enable+ Count=1/8 Maskable- 64bit+
	Kernel driver in use: xhci_hcd
```
Here is some captured traffic from Wireshark from when I tried out the different options of the application. I'm using Fedora 27 with kernel 4.14.8. Hope it helps.
[USBPackets_Maya22.pcapng.gz](https://github.com/rabits/esi-maya22-linux/files/1592332/USBPackets_Maya22.pcapng.gz)

**Comment by awk0324** [comment]
yeah, same issue here:
Linux screamingcat 4.15.9 #1 SMP Thu Mar 15 01:40:04 CET 2018 x86_64 GNU/Linux
00:1a.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 (rev 05)

Another fun fact, just tried the card on a Thinkpad x220 running debian9. Also an Intel USB controller, same erratic bahavior (e.g. once you try to set volume on a channel it switches off and remains silent), but the headphone output works by default! Also, if you fiddle with the settings and (I assume) set the card in some weird state, return to default settings (via -d switch) restores the headphone output. 

So the card works on USB3 port of a x220 running Debian stretch and at the same time it does not work on a USB2.0 port of the same machine.

**Comment by rabits** [comment]
Added workaround for intel chipsets - separated init operation 583385aac103d4a5054fe7e7474e498672463872 . So instead of `-d` in udev rule you can use `-i` and headphone will work fine.

Unfortunately it's just a workaround that don't fixes the issue, so need additional testing.

**Comment by PumbaPe** [comment]
Headphones indeed work instantly now, this is already very helpful! Thank you a lot!

**Comment by rabits** [comment]
Ok, seems I found the root cause - when we setting defaults it sends multiple requests without waiting for the response from each other, so device can't handle it and getting weird.
Also applied a couple of changes from #5 - Thanks @Psy-Kai for his help. Added his GUI app to the readme.
