### ISSUE TITLE
Not working properly under Fedora 27

### ISSUE THREAD

**Issue by PumbaPe** [rabits/esi-maya22-linux#2]
After some fiddling around I got the tool to work on my system (had to remove the GROUP parameter from the udev rule), but it's behaving quite erratically. I have to randomly change input channels and turn on and off the monitoring in order to hear the sound output from the computer at some point either through the sound cards output channels or the monitor/headphone jack. And even then it doesn't necessarily match the settings (e.g. sometimes I get sound from the monitor/headphone even though and sometimes only after I turn monitoring off). And sometimes there is a lot of background noise on the monitor while at other times there is very little. I couldn't find any reliable order of steps to finally get output, it seems very random. On Windows with the official driver everything works fine. Any idea what this could be about?

**Comment by rabits** [comment]
Yeah, you can check issue #1 to get some details. Unfortunately right now I can't test the card properly, but should get the chance on the next week.

**Comment by rabits** [comment]
Seems like issue in Intel USB controller - could you please check your USB controller (`lspci -v` will help) and post information about your hardware in the issue #1.
For now I will close it as a duplication.
