### ISSUE TITLE
Headphone output randomly working

### ISSUE THREAD

**Issue by Psy-Kai** [rabits/esi-maya22-linux#3]
On both my PC and my notebook I the headphone output does not work until I calll -L and/or -R option and then randomly call -m/-M. Mostly only one site of headphone work (only right speaker for example). But after spamming the different options (-L, -R, -m, -M) several times I managed to make booth speaker working. I don't think that this is the desired behavior.

**Comment by rabits** [comment]
Yeah, it's a bug #1 , unfortunately I didn't found how to fix it still...
