### ISSUE TITLE
New GUI utility

### ISSUE THREAD

**Issue by ghost** [rabits/esi-maya22-linux#4]
Hello! I make a GUI application for control MAYA22 USB under Linux. Maybe this will be useful.
https://sourceforge.net/projects/maya22gui/

**Comment by rabits** [comment]
Hi @cekmsu,
Sorry for the late answer, but finally get a chance to check your application on my intel macbook with linux 16.04 & connected headphones. Unfortunately I see no differences in logic in your application and testing shows the same issues we have in #1.

**Comment by rabits** [comment]
Hi @cekmsu , seems I just found why it's working weird before - please check #1 and commit 74b543c.

**Comment by ghost** [comment]
Wonderful! Now my application also works via USB hub.
And I found additional functionality:

Command 0x1a
---

- Bit0: 0 - normal mode; 1 - "mysterious mode".
- Bit3: 0 - headphones on; 1 - headphones off.
- Bit6: 0 - monitoring on; 1 - monitoring off.

Command 0x2c
---

- Bit0: 0 - playback off (mute); 1 - playback on.
- Bit2: 0 - monitoring off; 1 - monitoring on.

Monitoring enabled only if both commands used.
