### ISSUE TITLE
Information about communication protocol

### ISSUE THREAD

**Issue by Psy-Kai** [rabits/esi-maya22-linux#5]
Hello. I sent a request to ESI and got a header containing example code for how to program the Maya22USB. So here is what you could help you (especially with #1):
The size of the [array](https://github.com/rabits/esi-maya22-linux/blob/master/maya22-control.c#L47) needs to be 32 bytes, not 28.
The following values in the array are static:
```
char buffer[32];
memset(buffer, 0, sizeof(buffer));
buffer[1] = 0x12;
buffer[2] = 0x34;
buffer[3] = command;
buffer[5] = 1;
buffer[6] = data;
buffer[22] = 0x80;
```
`command` ad `data` can be the following values:

Description | `command` | possible `data`
-|-|-
enable headphone | `0x0D << 1` | `1` (dont know how to disable)
switch monitoring | `0x16 << 1` | enable: `5`; disable: `1`
volume out left | `(0x03 << 1) + 1` | range from `110` to `255`
volume out right | `(0x04 << 1) + 1` | range from `110` to `255`
volume in left | `0x0E << 1` | range from `104` to `231`
volume in right | `0x0F << 1` | range from `104` to `231`
select input | `0x15 << 1` | See following table

Input | `data` value
-|-
Mic | `1`
HiZ | `2`
Line | `4`
MicHiz | `8`

To mute an input, you select an input and mask its value with `0xC0`. So if you selected "MicHiZ" and want to mute it you need to send `0xC8`.

I still do not know how to enable monitoring. But with this information you should be able to fix some bugs (like breaking everything when setting some output volume level lower than 110).

PS: I created my own, heavy, Qt-based [control panel](https://gitlab.com/Psy-Kai/ESI-Maya22USBControl). If you need more information you could crawl my projects repo.

**Comment by rabits** [comment]
Hi @Psy-Kai , it definitely will help! Thank you very much)

**Comment by ghost** [comment]
Hi @Psy-Kai 

See #4 for headphone and monitoring control.

**Comment by Psy-Kai** [comment]
Added moniotoring to original issue. Forgot to add since I got that info from ESI too.
